### ISSUE TITLE
Se puede subir cualquier tipo de archivo como icono de una matera

### ISSUE THREAD

**Issue by atorres16** [atorres16/ReticulasEmpleados#6]
Restringir a ico png bmp jpg

**Comment by jass180194** [comment]
Se coloco una restriccion de acceso a archivo unicamente de tipo imagen de forma no explicita. Falta no permitir que cambien la opcion a todos los archivos.

**Comment by jass180194** [comment]
Se valido la aceptacion de archivos de tipo gif jpg jpeg bmp png
